return {
  -- This is what powers LazyVim's fancy-looking
  -- tabs, which include filetype icons and close buttons.
  -- icons
  -- {
  --   "echasnovski/mini.icons",
  --   lazy = true,
  --   opts = {
  --     file = {
  --       [".keep"] = { glyph = "󰊢", hl = "MiniIconsGrey" },
  --       ["devcontainer.json"] = { glyph = "", hl = "MiniIconsAzure" },
  --     },
  --     filetype = {
  --       dotenv = { glyph = "", hl = "MiniIconsYellow" },
  --     },
  --   },
  --   init = function()
  --     package.preload["nvim-web-devicons"] = function()
  --       require("mini.icons").mock_nvim_web_devicons()
  --       return package.loaded["nvim-web-devicons"]
  --     end
  --   end,
  -- },

  -- -- ui components
  -- { "MunifTanjim/nui.nvim", lazy = true },

  -- {
  --   "snacks.nvim",
  --   opts = {
  --     indent = { enabled = true },
  --     input = { enabled = true },
  --     notifier = { enabled = true },
  --     scope = { enabled = true },
  --     scroll = { enabled = true },
  --     statuscolumn = { enabled = false }, -- we set this in options.lua
  --     -- toggle = { map = LazyVim.safe_keymap_set },
  --     words = { enabled = true },
  --   },
  --   -- stylua: ignore
  --   keys = {
  --     { "<leader>n", function()
  --       if Snacks.config.picker and Snacks.config.picker.enabled then
  --         Snacks.picker.notifications()
  --       else
  --         Snacks.notifier.show_history()
  --       end
  --     end, desc = "Notification History" },
  --     { "<leader>un", function() Snacks.notifier.hide() end, desc = "Dismiss All Notifications" },
  --   },
  -- },
}
